### PR TITLE
Add LibratoBatchBuilder with default values for easier API

### PR DESCRIPTION
**Pull request by paulwellnerbou**
See objections in #30

### CODE REVIEW

**Comment by collinvandyck** [comment]
@paulwellnerbou thanks!  we'll take a look shortly.

**Comment by mheffner** [comment]
We are now tracking the latest client at https://github.com/appoptics/appoptics-api-java.

**Comment by paulwellnerbou** [comment]
@mheffner , @collinvandyck , as I am not using this anymore, I won't spent more time in this pull request. As this did not get merged, I created my own version, which I think has a much more nice API (see https://github.com/librato/librato-java/issues/32 as well)
Feel free to use my code. I won't keep my branch up to date for more than two years.

**Comment by mheffner** [comment]
Thanks @paulwellnerbou for the explanation. We have actually recently [added](https://github.com/librato/librato-java/pull/49) the OkHttpPoster based on [OkHttp](https://square.github.io/okhttp/) as an alternative Poster, as it provided better support for connection reuse and http/2 handling. This reduced the number of "connect failed" attempts we would see from clients reporting frequently since they didn't have to reestablish a new connection each time.

We plan to make this poster the default in the future, we're just ensuring it is completely stable. It sounds like you are not using Librato anymore, but if you have an opportunity to give Librato/AppOptics a try in the future give the OkHttpPoster a shot.

**Comment by paulwellnerbou** [comment]
@mheffner, thanks for your answer. The mentioned problem was not the motivation of this pull request.
I reduced the lines of code to use librato (as most users do, I suspect) and made it much more easier, and, at the same time using the Builder, not cutting flexibility.

But maybe that the current API changed in this direction as well. This is a long time ago...

**Pull request closed without merging**
